version: "3.9"

services:
  pyspark:
    build: .
    container_name: pyspark-lab
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/app/notebooks
    environment:
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=jupyter
      - PYSPARK_DRIVER_PYTHON_OPTS=lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
