[project]
name = "delta-ice"
version = "0.1.0"
description = "Ambiente PySpark + Delta Lake + Iceberg"
requires-python = ">=3.11"

dependencies = [
    "pyspark>=3.5.1",
    "delta-spark>=3.3.1",
    "pyiceberg>=0.10.0",
    "jupyterlab>=4.2.3"
]
